name: Create Sismo Connect App

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create Sismo Connect App on the factory
        run: yarn sync-all-apps-factory
        env:
          SISMO_FACTORY_URL: https://factory-api.staging.zikies.io
          SISMO_FACTORY_TOKEN: ${{ secrets.SISMO_FACTORY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push filled appId
        run: |
          git config --global user.email "robot@sismo.com"
          git config --global user.name "Sismo Robot"
          git add -A
          git commit -m "feat: create and fill appId" || exit 0
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add PR comment
        uses: actions/github-script@v5
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'App created on the factory!'
            })
