name: Upload zkDrop Metadata

on:
  issue_comment:
    types: [created]

jobs:
  create-app:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/upload-metadata')
    steps:
      - name: Check if sismo-core organisation member
        id: is_organization_member
        uses: jamessingleton/is-organization-member@1.0.0
        with:
          organization: "sismo-core"
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.is_organization_member.outputs.result != 'true'
        run: exit 1

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{secrets.SISMOBOT_TOKEN}}

      - name: Checkout Pull Request
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.SISMOBOT_TOKEN }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Get modified spaces and apps
        id: updated-spaces
        run: |
          echo 'Changed files:'
          DEMO_UPDATED_SPACES=$(git diff --name-only origin/main -- 'space-configs/demo')
          echo "::set-output name=demo_updated_spaces::$(echo "$DEMO_UPDATED_SPACES")"
          MAIN_UPDATED_SPACES=$(git diff --name-only origin/main -- 'space-configs/main')
          echo "::set-output name=main_updated_spaces::$(echo "$MAIN_UPDATED_SPACES")"

      - name: Display changes
        run: |
          echo "[DEMO] Modified spaces and apps in commit:"
          echo "${{ steps.updated-spaces.outputs.demo_updated_spaces }}"
          echo "[MAIN] Modified spaces and apps in commit:"
          echo "${{ steps.updated-spaces.outputs.main_updated_spaces }}"